Document: subutai-dhcp
Title: Debian subutai-dhcp Manual
Author: <insert document author here>
Abstract: This manual describes what subutai-dhcp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/subutai-dhcp/subutai-dhcp.sgml.gz

Format: postscript
Files: /usr/share/doc/subutai-dhcp/subutai-dhcp.ps.gz

Format: text
Files: /usr/share/doc/subutai-dhcp/subutai-dhcp.text.gz

Format: HTML
Index: /usr/share/doc/subutai-dhcp/html/index.html
Files: /usr/share/doc/subutai-dhcp/html/*.html
